// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/normal/Footer.vue')['default']
    Header: typeof import('./src/components/normal/Header.vue')['default']
    LogoSvg: typeof import('./src/components/naiveWelcomeLayout/LogoSvg.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NaiveButton: typeof import('./src/components/NaiveButton.vue')['default']
    NaiveFooter: typeof import('./src/components/normal/NaiveFooter.vue')['default']
    NaiveHeader: typeof import('./src/components/normal/NaiveHeader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}

export {}
